#ifndef REPORT_TYPE
#define REPORT_TYPE

enum class ReportType {
    SECURITY_REQUIRED, 
    MEDICAL_REQUIRED, 
    FACILITIES_REQUIRED, 
    ALERT_REQUIRED,
    ACCESS_CONTROL_REQUIRED,
    AREA_UNSAFE, 
    EVACUATION_REQUIRED, 
    INCIDENT_REPORTED, 
    INCIDENT_REPORT_WITHDRAWN
};

#endif